### PR TITLE
add writeCoils

### PR DESCRIPTION
**Pull request by postgetme**
writeCoils(dataAddress: number, states: Array<boolean>): Promise<WriteMultipleResult>;

### CODE REVIEW

**Comment by yaacov** [comment]
👍

**Comment by yaacov** [comment]
hi, do you need this on npm ?

**Comment by postgetme** [comment]
hi, why npm involves?

**Comment by yaacov** [comment]
> hi, why npm involves?

if you want to do `npm install ... ` . Until I publish a new release with your change, `npm install ... ` will install a version without your change.

**Comment by postgetme** [comment]
got it. it's doesn't matter, the current version is ok, I can update this package later.

**Comment by yaacov** [comment]
np :-)

**Pull request merged**
