### PR TITLE
Remove listeners on close tcp buffered

### PR DESCRIPTION
**Pull request by yaacov**
@robertsLando  can you check if this solves the issue in #371 ?

### CODE REVIEW

**Comment by robertsLando** [comment]
@yaacov Yes it does!

**Comment by robertsLando** [comment]
@yaacov I'm wondering if it would be correct to also remove listeners from `this._client`. What do you think?

**Comment by yaacov** [comment]
> @yaacov I'm wondering if it would be correct to also remove listeners from this._client. What do you think? On close event I mean

IMHO no, unless it creates a problem for someone :-)

**Comment by robertsLando** [comment]
:+1:

**Pull request merged**
