### PR TITLE
fix: duplicate close callback call ModbusTCP

### LINKED ISSUE #413: Close event `cb` is emitted twice with version `8.0.2`
8.0.2 has broke all my test suites as now seems that close event callback is called twice, it's a regression introduced in latest commits

### PR DESCRIPTION
**Pull request by robertsLando**
Fixes #413

### CODE REVIEW

**Comment by yaacov** [comment]
:green_heart:

**Comment by robertsLando** [comment]
@yaacov Patch release please? :)

**Comment by robertsLando** [comment]
Sorry @yaacov for pinging you again, I would like to fix this issue on my repos could you make a new patch release please?

**Comment by yaacov** [comment]
np :-)

https://www.npmjs.com/package/modbus-serial/v/8.0.3

**Comment by robertsLando** [comment]
Thanks :)

**Pull request merged**
