### PR TITLE
Update asciiport.js

### PR DESCRIPTION
**Pull request by ThKls**
Issue with slave replies.

### CODE REVIEW

**Comment by yaacov** [comment]
hi, thank you for the patch :+1: 

can you look at the failing tests ?

**Comment by ThKls** [comment]
Hi,  

The tests expect replies starting with ‚:‘ (3A hex). This is not correct according to Modbus ASCII Standard, which stated replies starting with ‚>‘ (3E hex). My fault, due to my lack of experience with Github CI testing, I missed to change test procedures as well. I can confirm, that the change works with my ABL eMHL car charger.

**Comment by yaacov** [comment]
ok, can you fix the tests ?

**Comment by ThKls** [comment]
Has been done. You should see the new fix.

**Comment by yaacov** [comment]
closing in favor of #395

**Comment by yaacov** [comment]
Thanks :-)

**Pull request closed without merging**
