### PR TITLE
better docs first step

### PR DESCRIPTION
**Pull request by biancode**
- same debug log for all ports
- some doc strings to generate docs ( gulp docs)

### CODE REVIEW

**Comment by biancode** [comment]
after `gulp docs` watch ./docs/gen/index.html

**Comment by biancode** [comment]
tests are green on npm test

**Comment by biancode** [comment]
some cleanup for private state of functions in different ports

**Comment by yaacov** [comment]
Thanks ! 👍

**Comment by yaacov** [comment]
v5.3.1 in npm :-)

**Pull request merged**
