### PR TITLE
Fix callback bit offset FC1/FC2 beeing forced to 0

### PR DESCRIPTION
**Pull request by NicolasDuran**
FC1 and FC2 callback had a bit offset forced to 0.
If doing a FC1/FC2 request on multiple adresses, only the first result was set

### CODE REVIEW

**Comment by yaacov** [comment]
whoo, nice ! I think I did that ...
will merge when green :-)

**Comment by yaacov** [comment]
p.s.
if you have time, we need tests for this part of the code ... just if you have time :-)

**Comment by yaacov** [comment]
@NicolasDuran need linting fix ^

**Comment by NicolasDuran** [comment]
I will try to add tests if I have time in the next days :)

**Pull request merged**
