### PR TITLE
Fix destroy callback never to be called

### PR DESCRIPTION
**Pull request by narttmk**

### CODE REVIEW

**Comment by yaacov** [comment]
thanks :green_heart:

**Comment by AndreMaz** [comment]
@yaacov was this released? If the answer is no, can you please do it?

**Comment by yaacov** [comment]
https://www.npmjs.com/package/modbus-serial/v/8.0.17 - :tada: :cake:

**Comment by AndreMaz** [comment]
Super! Thank you :+1:

**Pull request merged**
