### PR TITLE
README and generated JSDoc

### PR DESCRIPTION
**Pull request by biancode**
- gulp to build docs, cleanup, and to organize npm content
- README update for Wiki use
- first JSDoc example in rtutcp module

### CODE REVIEW

**Comment by biancode** [comment]
you can use gulp with:

`gulp docs`

`gulp build`

or both with

`gulp publish`

**Comment by biancode** [comment]
npm-update and npm-upgrade can be used to update or upgrade all used npm packages - be careful with the upgrade script - mostly I'm using the update and from major to major the upgrade script

**Comment by biancode** [comment]
gulp clean removes all generated stuff

**Comment by yaacov** [comment]
Great !! merged 🎉 🍰

**Pull request merged**
