### PR TITLE
WriteMultipleRegisters added callback and promises workflow

### PR DESCRIPTION
**Pull request by HighWolf**
- prevent _handleWriteMultipleRegisters send a response before executing setRegisterArray or setRegister.
- added promise control in _handleWriteMultipleRegisters setRegisterArray code block

### CODE REVIEW

**Comment by yaacov** [comment]
@HighWolf hi, can you look at the ci fails ?

**Comment by HighWolf** [comment]
@yaacov sorry for that, I just fixed the missing semicolon.

**Review by HighWolf — COMMENTED** [review]
improved workflow in _handleWriteMultipleRegisters changelog:
- buildCb function is not required since a single call-back function can handle the process if triggered in the right place.
- try-catch function combined for incoming data processing and setRegisterArray caller 

[OBSERVATIONS]
Call-back modification was done having in mind that only one response is accepted/needed. For that reason, call-back function must be called either when an error has occurred (error response) or when the process was complete (success response).

**Comment by yaacov** [comment]
still failing, try run `npm run test` and see what is failing

**Comment by HighWolf** [comment]
@yaacov Done. All tests(189) passed.

**Comment by HighWolf** [comment]
@yaacov is possible to generate a new release with the actual state of the master?

**Comment by yaacov** [comment]
https://www.npmjs.com/package/modbus-serial/v/8.0.6

:tada: :cake:

**Pull request merged**
