### PR TITLE
Ascii serial support

### PR DESCRIPTION
**Pull request by dom-white**
Hi I have added a new port to support the ASCII mode of serial.
It uses a different error correction method (lrc) but I have made this transparent to the higher levels by checking the lrc at the port level and swaping in a crc header for your higher level index.js to check. This is similar to the method you used for tcp port.

I have also tweaked the error detection logic in index.js to pick up exception responses correctly.

I have tested all of this using "Simply Modbus Slave 8.0.3" running in ASCII mode.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/yaacov/node-modbus-serial/pull/6" target="_blank">ReviewNinja

**Comment by yaacov** [comment]
Hi,
Thanks for the ascii  port.
And the white spaces :+1: and the fix of exception bug.

**Comment by yaacov** [comment]
p.s. can you add the ascii support to the readme ?

**Comment by dom-white** [comment]
Just created a new pull request for the ascii changes to the readme  (sorry about the unnecessary white space changes in the previous pull)

**Comment by yaacov** [comment]
I liked the spaces changes :+1:

**Pull request merged**
