### PR TITLE
Modbus Serial Server - including tests (still requires external devices)

### PR DESCRIPTION
**Pull request by 1038642892**
Good day to you,

I've been needing a Modbus serial server and have found some time to implement it from your TCP server code.

I do have tests for it but they are still reliant on a local set of linked virtual serial ports. Please see the test file for a description of how to invoke this in a Linux environment - once in place the tests will pass.

I'm looking for some feedback on the submission of code and help to get this through to master - including with an appropriate testing environment.

Thanks

### CODE REVIEW

**Comment by yaacov** [comment]
hmm, tests failing, can you take a look ?

**Comment by 1038642892** [comment]
> hmm, tests failing, can you take a look ?

"I do have tests for it but they are still reliant on a local set of linked virtual serial ports. Please see the test file for a description of how to invoke this in a Linux environment - once in place the tests will pass."

Are you aware of a non system specific way to test this?

**Comment by yaacov** [comment]
some tests that require serial connection use mockery [1],
https://github.com/yaacov/node-modbus-serial/blob/master/test/ports/rtubufferedport.test.js

can see if you can use it for you tests too ?

[1] https://github.com/mfncooper/mockery

**Comment by yaacov** [comment]
> use something else that allows us to connect the server and client in reality rather than a mock

both work for me

**Comment by 1038642892** [comment]
> > use something else that allows us to connect the server and client in reality rather than a mock
> 
> both work for me

I couldn't find a premade node solution, so i linked two serial interfaces using the @serialport/binding-mock.

**Comment by yaacov** [comment]
:bouquet: :cake:

**Pull request merged**
