### PR TITLE
avoid double callback when read timeout is hit

### PR DESCRIPTION
**Pull request by dom-white**
In the case where an Ethernet cable is pulled out before a read there will be a callback of the read function with an Error (whenthe timeout code fires). 

However if the cable is re-plugged, due to the nature of tcp (reliable transport/re-transmissions), data may now arrive and an additional callback for the same read can be generated.

It is not good practice to call a callback multiple times, and if the read was issued within an async module task (e.g. forEachOfSeries), async will throw an exception due to the double callback.

This patch adds detection of whether the timeout fired for the transaction and prevents any data received for this transaction 'after' this to be dropped rather than sent back via a 2nd call to the callback.

Ideally this data would be usable, but I don't think there is a way of getting this back to the callee without triggering a double callback. Plus this is an edge condition where the link has dropped, so loosing a little bit of data would be acceptable.

### CODE REVIEW

**Comment by yaacov** [comment]
👍 Thanks

**Comment by dom-white** [comment]
Thanks for merging this in. It all looks good to me now. Is it possible to create a new npm release (again :-) )

**Comment by yaacov** [comment]
7.0.3 is out

**Comment by dom-white** [comment]
brilliant. thanls

**Pull request merged**
