### PR TITLE
F43 RTUBuffered fix

### PR DESCRIPTION
**Pull request by oicnal**
Add F43 support to rtu-buffered port.

Fixes: #327

### CODE REVIEW

**Comment by yaacov** [comment]
Thanks, ping me when you have a working fix :+1:
p.s.
Feel free to ask for help, in comments here.

**Comment by oicnal** [comment]
I don't think we can computed the expected slave answer length for device identification as the answer is composed of vendor specific strings. 

ex:  {"data":{"0":"EPsolar Tech co., Ltd","1":"TriRon4210","2":"V01.54+V01.22"},"conformityLevel":1}

**Comment by oicnal** [comment]
Can I set the expected lenght to maximum? assuming rest of the code is able to deal with a smaller effective answer length.

**Comment by yaacov** [comment]
> Can I set the expected lenght to maximum? assuming rest of the code is able to deal with a smaller effective answer length.

You should add tests that will check your new functionality, make sure you do not change the functionality of other parts, feel free to add tests for that too.

 https://github.com/yaacov/node-modbus-serial/tree/master/test

**Comment by oicnal** [comment]
I understand the dev process, my question is about how the code works.

**Comment by yaacov** [comment]
> Can I set the expected lenght to maximum? 

You can try and play with the code to add the functionality you want.

The tests should guard you and help you not break things :-) . You can play with the length for f43 as you think is good as long as you make sure that the tests you make are full and simulate real world scenarios. 

If you feel that current tests are missing something, please add the missing tests even if they are not directly connected to the new feature.

**Comment by oicnal** [comment]
I did try some fix without any luck :( 
Since length of f43 answer can not be calculated, I propose to raise an error when using f43 with rtu buffered. 
A work around exist... use non buffered rtu to query device identification data.

**Comment by yaacov** [comment]
>  did try some fix without any luck :(

np.

> I propose to raise an error when using f43 with rtu buffered. `A work around exist... use non buffered rtu to query device identification data`.

We can also add to the README.md line 68 file a list of supported ports :
```
FC43/14 "Read Device Identification" (supported ports: TCP, RTU)
```
instead of 
```
FC43/14 "Read Device Identification"
```

**Comment by yaacov** [comment]
@oicnal do you want to fix it in this pull request or to close this one and open a new one for the error handling / and documentation ?

**Comment by oicnal** [comment]
lazy fixed!

**Comment by yaacov** [comment]
Thanks :green_heart:

feel free to continue investigating a complete fix :+1:

**Pull request merged**
