### PR TITLE
Update asciiport.js

### PR DESCRIPTION
**Pull request by behi88**
Thanks for the tips.

### CODE REVIEW

**Comment by yaacov** [comment]
Thanks great :exclamation: :smile: 
@behi88 can you fix the bad tests ?

**Comment by yaacov** [comment]
fixes: https://github.com/yaacov/node-modbus-serial/issues/235

**Comment by behi88** [comment]
you are welcome.
unfortunately i do not have any experience in mockery library.
actual i use this in my raspberry pi an my PC as client.
I could make a sample data string from those if it help.

**Comment by behi88** [comment]
by the way , great code.
I will continue to test all of this library options and keep you posted.

**Comment by yaacov** [comment]
@behi88 does that fix your problem ?

This should not work, because:

a. In cunctions 1, 2, 3 and 4 ( Read Coil Status, Read Input Status, Read Holding Registers and Read Input Registers ) the 3'rd  ( e.g. `data[2]` ) `byte` represent the  number of data bytes to follow. And in modbus ASCII `data byte` is actually two ASCII letters ( e.g. each `data byte` is 2 bytes in the buffer ).

b. In functions 5, 6,15 and 16 ( Force Single Coil, Preset Single Register, Force Multiple Coils and Preset Multiple Registers ) the 3'rd is not the number of data bytes to follow, it's the Data Address of the first register.

@behi88 

1. Please check again ... especially functions 5, 6, 15 and 16 for registers above `0x0f`
2. Can you paste one answer in ASCII and the translation to RTU ? 

For example:

1. ASCII
```
: 1 1  0 3  0 0  6 B  0 0  0 3  7 E  CR LF
```

2. ASCII buffer:
```
3A 3131 3033 3030 3642 3030 3033 3745 0D 0A
```

3. Should translate to RTU message:
```
11 03 00 6B 00 03 76 87
```

**Comment by behi88** [comment]
I checked for function (FC1,FC2,FC3,FC4)
all worked fine
here are some examples:


RX | Device:1 Function: 4 Address: 0 Quantity: 10 
3A-30-31-30-34-30-30-30-30-30-30-30-41-46-31-0D-0A


TX | Device:1 Function: 4 
3A-30-31-30-34-**32-38**-30-30-30-31-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-44-32-0D-0A

as you see 0x28 is the count of data characters = 40 
when yo combine every 2 characters in to one byte for (example (32-38) =>  0x28) numbr of result byte should be 1/2 of number of characters .
40 is the count of characters. so the count of bytes should be 20.

**Comment by behi88** [comment]
I will check the for FC5-FC6 , ...
but i don't think this would be problem there because we are changing the receive answer part.
the FC5,... are write command an do not have a receive part i think (i will double check).

**Comment by behi88** [comment]
the FC5 works fine but if return an 'undefined' on screen on every call:

 modbus-serial { action: 'send serial ascii port',
  modbus-serial   data: <Buffer 3a 30 31 30 35 30 30 30 30 46 46 30 30 46 42 0d 0a>,
  modbus-serial   unitid: 1,
  modbus-serial   functionCode: 5 } +0ms
  modbus-serial {"action":"send serial ascii port","data":{"type":"Buffer","data":[58,48,49,48,53,48,48,48,48,70,70,48,48,70,66,13,10]},"unitid":1,"functionCode":5} +15ms
  modbus-serial { action: 'receive serial ascii port',
  modbus-serial   data: <Buffer 3a 30>,
  modbus-serial   buffer: <Buffer 3a 30> } +30ms
  modbus-serial {"action":"receive serial ascii port strings","data":{"type":"Buffer","data":[58,48]},"buffer":{"type":"Buffer","data":[58,48]}} +1ms
  modbus-serial { action: 'receive serial ascii port',
  modbus-serial   data: <Buffer 31 30 35 30 30 30>,
  modbus-serial   buffer: <Buffer 3a 30 31 30 35 30 30 30> } +4ms
  modbus-serial {"action":"receive serial ascii port strings","data":{"type":"Buffer","data":[49,48,53,48,48,48]},"buffer":{"type":"Buffer","data":[58,48,49,48,53,48,48,48]}} +1ms
  modbus-serial { action: 'receive serial ascii port',
  modbus-serial   data: <Buffer 30 46 46>,
  modbus-serial   buffer: <Buffer 3a 30 31 30 35 30 30 30 30 46 46> } +1ms
  modbus-serial {"action":"receive serial ascii port strings","data":{"type":"Buffer","data":[48,70,70]},"buffer":{"type":"Buffer","data":[58,48,49,48,53,48,48,48,48,70,70]}} +1ms
  modbus-serial { action: 'receive serial ascii port',
  modbus-serial   data: <Buffer 30>,
  modbus-serial   buffer: <Buffer 3a 30 31 30 35 30 30 30 30 46 46 30> } +0ms
  modbus-serial {"action":"receive serial ascii port strings","data":{"type":"Buffer","data":[48]},"buffer":{"type":"Buffer","data":[58,48,49,48,53,48,48,48,48,70,70,48]}} +1ms
  modbus-serial { action: 'receive serial ascii port',
  modbus-serial   data: <Buffer 30 46>,
  modbus-serial   buffer: <Buffer 3a 30 31 30 35 30 30 30 30 46 46 30 30 46> } +1ms
  modbus-serial {"action":"receive serial ascii port strings","data":{"type":"Buffer","data":[48,70]},"buffer":{"type":"Buffer","data":[58,48,49,48,53,48,48,48,48,70,70,48,48,70]}} +1ms
  modbus-serial { action: 'receive serial ascii port',
  modbus-serial   data: <Buffer 42>,
  modbus-serial   buffer: <Buffer 3a 30 31 30 35 30 30 30 30 46 46 30 30 46 42> } +1ms
  modbus-serial {"action":"receive serial ascii port strings","data":{"type":"Buffer","data":[66]},"buffer":{"type":"Buffer","data":[58,48,49,48,53,48,48,48,48,70,70,48,48,70,66]}} +1ms
  modbus-serial { action: 'receive serial ascii port',
  modbus-serial   data: <Buffer 0d>,
  modbus-serial   buffer: <Buffer 3a 30 31 30 35 30 30 30 30 46 46 30 30 46 42 0d> } +0ms
  modbus-serial {"action":"receive serial ascii port strings","data":{"type":"Buffer","data":[13]},"buffer":{"type":"Buffer","data":[58,48,49,48,53,48,48,48,48,70,70,48,48,70,66,13]}} +1ms
  modbus-serial { action: 'receive serial ascii port',
  modbus-serial   data: <Buffer 0a>,
  modbus-serial   buffer: <Buffer 3a 30 31 30 35 30 30 30 30 46 46 30 30 46 42 0d 0a> } +1ms
  modbus-serial {"action":"receive serial ascii port strings","data":{"type":"Buffer","data":[10]},"buffer":{"type":"Buffer","data":[58,48,49,48,53,48,48,48,48,70,70,48,48,70,66,13,10]}} +1ms
  modbus-serial { action: 'got EOM',
  modbus-serial   data: <Buffer 01 05 00 00 ff 00 8c 3a>,
  modbus-serial   buffer: <Buffer 3a 30 31 30 35 30 30 30 30 46 46 30 30 46 42 0d 0a> } +2ms
  modbus-serial { action: 'emit data serial ascii port',
  modbus-serial   data: <Buffer 0a>,
  modbus-serial   buffer: <Buffer 3a 30 31 30 35 30 30 30 30 46 46 30 30 46 42 0d 0a> } +1ms
undefined

**Comment by behi88** [comment]
it is actually the software on my PC by 'ELSETA' corporation.
it is a protocol analyze software. I have few modbus software on my PC, let me try another one

**Comment by behi88** [comment]
TX | Device:1 Function: 4
3A-30-31-30-34-32-38-30-30-30-31-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-30-44-32-0D-0A

3A         => :
30-31    => 0x01 (Device code)
30-34    => 0x04 (Function code FC4)
38-30    => 0x28 (Number of followed character)
.
.
.

**Comment by behi88** [comment]
bad news, my other software do not support ASCII mode. but I am searching :)

**Comment by behi88** [comment]
I found 2 software like "Modbus tools" and "simply Modbus" that support ASCII mode but the library could not parse the answer.
I will work on them and keep you informed.

**Comment by yaacov** [comment]
> I will work on them and keep you informed.

Sorry for making you work so hard ... but I do not want to add a fix that will work for one software/device but will break other  one.

p.s.
a. I do not have a "certified" ASCII modbus machine to check with :-)

b. I think that the ASCII variant that send double length is the less common one.

c. @biancode , can you help here ?

**Comment by behi88** [comment]
Do not worry I will find one

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by behi88** [comment]
I contacted "elseta vinci expert" company about their software and ask to double check the result. I  hope to have an answer in next few days
I also checked "simply Modbus" and "Modbus tools" software, they are both using byte count , not character count (that i think is much reasonable now)
I ask if their  software are Modbus certified. hope to have answer in few days too.
the best answer that i could find online was from www.modbus.org itself.
and the simplified answer is in here too:
http://www.simplymodbus.ca/ASCII.htm

**Comment by behi88** [comment]
for now I suggest you don't add my code to your library

**Comment by yaacov** [comment]
@behi88 @biancode Thanks, I will ask too, if I will also get the answer that in ASCII the length is of message bytes, I will fix this.

Note: @biancode if we decide that we need to fix this, this will change the behaviour of ASCII modbus.

**Comment by behi88** [comment]
Hi
the "Modbus tools" answered  yesterday and they said they do not have certificate on their software but they could pass the test if they apply for certificate!
but I am still waiting for answer on ELSETA' corporation.
for now the best answer that I could find is it should be register count.
I'm thinking it would be nice to add byte count check error to the modbus packets.

**Comment by yaacov** [comment]
>  I'm thinking it would be nice to add byte count check error to the modbus packets.

a. :+1: 

b. You should add a check to divide only for function codes 1, 2, 3 and 4, other function codes do not have this field.

**Comment by yaacov** [comment]
hi, sorry this took so long, closing for now.

**Pull request closed without merging**
