### PR TITLE
Add an errno to port not open error

### PR DESCRIPTION
**Pull request by yaacov**
**Description**
Add an errno to the error emitted when trying to send a modbus commad on a closed port.

Change the logger.js example to use the new errno.

### CODE REVIEW

**Comment by yaacov** [comment]
@joshuatreenl @biancode @connium please review, this may fix #92

I can't reproduce the bug of #92, @joshuatreenl @biancode please try to check if this helps ?

**Comment by joshuatreenl** [comment]
I installed the *new* logger.js.  No improvement, the e.catch seems to be not working. 

see: 
[20170331 1030 loggerA_js.txt](https://github.com/yaacov/node-modbus-serial/files/884980/20170331.1030.loggerA_js.txt)

**Comment by yaacov** [comment]
@joshuatreenl this logger.js need the new code in index.js,

From your txt log it looks like you are using the master branch. did you use the index.js in this pull request ?

I can just make a new version with this chage, so you could just do `npm install`, If you do not know how to do this.

**Comment by yaacov** [comment]
@joshuatreenl thanks for the log you attached to the issus 👍

What I understand from it is that we do know that we get an ECONNRESET from the server, but we do not pass that error upward. 
So I made a small change https://github.com/yaacov/node-modbus-serial/pull/93/commits/74255b6db34f2b515bc01b12673cae377e1153f6 that may help here

p.s
It is a bit tricky to use a pull request if you do not know git, you can just download this file -
https://github.com/yaacov/node-modbus-serial/archive/add-errno-to-port-no-open.zip

I think that in your last test you used code from the master repository, and that is why you got the log file you sent

**Comment by joshuatreenl** [comment]
@yaacov  

Two conclusions: 
- Yes I have to learn a lot of how to use git 
- Yes i learned a lot in the past days... 

What I did is remove the modbus-serial branch and perform an install via:
npm install modbus-serial --unsafe-perm --build-from-source 
Everything was build and I went to the examples directory and made the DEBUG=...

The steps I will do next:
- Download add-errno-to-port-no-open.zip
- unpack
- Copy to my device.
- Goto the examples and execute the logger.js (after modifying the ip-address

Right? OR do i miss the build of add-errno-to-port-no-open?

**Comment by joshuatreenl** [comment]
Get the following message:

root@iot2000:/usr/lib/node_modules/node-modbus-serial-add-errno-to-port-no-open/examples# DEBUG=modbus-serial node logger.js
module.js:340
    throw err;
    ^

Error: Cannot find module 'serialport'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/lib/node_modules/node-modbus-serial-add-errno-to-port-no-open/ports/rtubufferedport.js:5:18)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)

**Comment by yaacov** [comment]
```
The steps I will do next:

    Download add-errno-to-port-no-open.zip
    unpack
    Copy to my device.
    Goto the examples and execute the logger.js (after modifying the ip-address

Right? OR do i miss the build of add-errno-to-port-no-open?
```

A. Sounds correct 👍 
B. the example use `../index.js` instead of `modbus-serial` so you will not have to build :-)

**Comment by yaacov** [comment]
p.s.
node-red will use the old version, until we make a new version and @biancode will adapt it to node red.

**Comment by joshuatreenl** [comment]
See post before "the error in module.js"

**Comment by yaacov** [comment]
`Error: Cannot find module 'serialport'`

ahh, i was not correct, we do need to build ...  BUT, the new zip file is updated in a way that should bypass that need :-) 
https://github.com/yaacov/node-modbus-serial/archive/add-errno-to-port-no-open.zip

**Comment by joshuatreenl** [comment]
I have modified the index.js code as mentioned: same problem

root@iot2000:/usr/lib/node_modules/node-modbus-serial-add-errno-to-port-no-open/examples# DEBUG=modbus-serial node logger.js
module.js:340
    throw err;
    ^

Error: Cannot find module 'serialport'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/lib/node_modules/node-modbus-serial-add-errno-to-port-no-open/ports/rtubufferedport.js:5:18)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)

**Comment by joshuatreenl** [comment]
Mails crossed.... I will download the new zip file. Wait a moment.

**Comment by joshuatreenl** [comment]
almost...

root@iot2000:/usr/lib/node_modules/node-modbus-serial-add-errno-to-port-no-open/examples# DEBUG=modbus-serial node logger.js
path.js:424
    var path = (i >= 0) ? arguments[i] : process.cwd();
                                                 ^

Error: ENOENT: no such file or directory, uv_cwd
    at Error (native)
    at Object.posix.resolve (path.js:424:50)
    at startup (node.js:93:32)
    at node.js:963:3

**Comment by joshuatreenl** [comment]
@yaacov  Remember the vesion of node installed is v4.2.4! Maybe that's the problem?

**Comment by yaacov** [comment]
`@yaacov Remember the version of node installed is v4.2.4! Maybe that's the problem?`

if v4.2.4 is not compatible then the code you had before should have failed too ... the only difference is not running the build ... 

I'm looking what is the problem, maybe I will make a new version, this changes are small and shouldn't harm anything

**Comment by joshuatreenl** [comment]
> if v4.2.4 is not compatible then the code you had before should have failed too ... the only difference is not running the build ... <
You are right, that make sense. 

For me it is no problem to clean my device an build it again.

**Comment by yaacov** [comment]
looked at google :-)

It looks like something with copying and pasting the files and naming of directories  ... not connected to the code ...
a possible fix will be to delete completely the old directories and after copying the new version rename it to `modbus-serial` in case we need the currect name of the directory somewhere

**Comment by yaacov** [comment]
> delete completely the old directories 

p.s.
I am meaning the `modbus-serial` and `node-modbus-serial-add-errno-to-port-no-open` ones , not the whole system

**Comment by joshuatreenl** [comment]
- Removed modbus-serial and node-modbus-serial-add-errno-to-port-no-open
- Renamed the last version of node-modbus-serial-add-errno-to-port-no-open -> modbus-serial
- Modified the logger.js (ip-address)
- Executed in the examples directory: DEBUG=modbus-serial node logger.js

Result: 

[20170331 1330 loggerA_js.txt](https://github.com/yaacov/node-modbus-serial/files/885435
/20170331.1330.loggerA_js.txt)

**Comment by yaacov** [comment]
Last change promise :-) 🤞 

Just copy the new logger.js ( this time no change to rest of the library )
https://github.com/yaacov/node-modbus-serial/blob/7701a7382ba9aa5d822564e6a2d0ba1cbb7ab31b/examples/logger.js

**Comment by joshuatreenl** [comment]
- Copied the modified logger.js to my device
- Executed in the examples directory: DEBUG=modbus-serial node logger.js

Result:

[20170331 1347 logger_js.txt](https://github.com/yaacov/node-modbus-serial/files/885478/20170331.1347.logger_js.txt)

I think the next step is to reconnect. But that should be modified in 'the user' program.

**Comment by yaacov** [comment]
> I think the next step is to reconnect. But that should be modified in 'the user' program.

the logger example i linked to, should have tried to reconnect, can you run it for some longer time and then anable the server again ?

**Comment by joshuatreenl** [comment]
I would love to do that but the program automatically stops:

<RENE --- DISABLED THE SERVER

  modbus-serial TCP port: signal error: Error: read ECONNRESET +471ms
  modbus-serial { action: 'port open error',
  modbus-serial   error: { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } } +3ms
  modbus-serial TCP port: signal close: true +27ms
  modbus-serial { action: 'port open error', error: true } +4ms

<RENE -- I did nothing to stop...

root@iot2000:/usr/lib/node_modules/modbus-serial/examples#

**Comment by yaacov** [comment]
> I would love to do that but the program automatically stops:
😄 

ahh ... I can't reproduce what you have, so I'm writing blind, but I think this solve my last mistake :-)

https://github.com/yaacov/node-modbus-serial/blob/52e631536e7ef618e71b48e8b1e1959b9d3de4c8/examples/logger.js

**Comment by joshuatreenl** [comment]
No improvement -- sorry -- 
Same as before, stops immediately. If I disconnect via the network connector I get a timeout, but in the case of disable the server not.

[20170331 1420 logger_js.txt](https://github.com/yaacov/node-modbus-serial/files/885566/20170331.1420.logger_js.txt)

**Comment by joshuatreenl** [comment]
Mailing crossed again. Wait a moment I install the new version

**Comment by joshuatreenl** [comment]
Same, no improvement 

[20170331 1431 logger_js.txt](https://github.com/yaacov/node-modbus-serial/files/885585/20170331.1431.logger_js.txt)

**Comment by yaacov** [comment]
I have reverted the change I made to not stopping sending the error after sending it once.
I think that sending it more then once ( I did that because I thought it was clever :-) ) break the program ... It doesn't happen to me because I don't have that error, and I do not try to sent it twice :-(

to test it you will have to get the whole library again ( the change back is in the tcpport.js ) or just replace the tcpport.js
a. whole lib: https://github.com/yaacov/node-modbus-serial/archive/add-errno-to-port-no-open.zip
b. only rolled back tcpport: https://github.com/yaacov/node-modbus-serial/blob/31979fcd8d8c1eaf0e03b7886cbcc0088f771add/ports/tcpport.js

**Comment by yaacov** [comment]
If the above fix doesn't work, I will try to get a device that does `ECONNRESET`and fix it with a device connected, so I can check the fixes myself ...

**Comment by joshuatreenl** [comment]
@yaacov:

- Downloaded a. 
- Unpack a. and renamed to node-modbus-serial
- Copy to device
- Executing: /usr/lib/node_modules/node-modbus-serial/examples# DEBUG=modbus-serial node logger.js

[20170331 1530 logger_js.txt](https://github.com/yaacov/node-modbus-serial/files/885793/20170331.1530.logger_js.txt)

Same output. 
I''l hope this error will be managed in the future. Thanks for all your help. I also will be thinking what could be wrong. If I have a solution or workaround I'll let you know.

**Comment by yaacov** [comment]
> If I have a solution or workaround I'll let you know.

Great 👍 i think that once I get a machine to do ECONNRESET i will fix it, it doesn't look complicated, just need to see it for my self :-)

**Comment by joshuatreenl** [comment]
Of course that should be fine. The odd thing of course is that the physical network connection is allright. Therefor the connection is made. But then things goes wrong deeper in the Modbus layers. Did you try to setup a server by yourself and make contact with your client. What happens if you kill the Modbus Server process on the other side? Does it have the same error?

**Comment by yaacov** [comment]
@biancode @joshuatreenl this does not solve https://github.com/yaacov/node-modbus-serial/issues/92 but it is a very small fix and it does not change anything except debug outputs, merging.

Will try again to fix https://github.com/yaacov/node-modbus-serial/issues/92 once I set up a device that recreates this bug.

**Comment by yaacov** [comment]
> What happens if you kill the Modbus Server process on the other side? Does it have the same error?

I used modbus machines on the internet, so I will not need to set up a test machine :-) , I will set up a test machine or a pc-mock in my office and look into it more carefully ...

**Comment by yaacov** [comment]
> What happens if you kill the Modbus Server process on the other side? Does it have the same error?

@joshuatreenl , No that doesn't do it :-)

**The server:**
```
kobi@desk1:~/Projects/node-modbus-serial/examples(master)$ node server.js 
ModbusTCP listening on modbus://0.0.0.0:8502
^C
kobi@desk1:~/Projects/node-modbus-serial/examples(master)$ node server.js 
ModbusTCP listening on modbus://0.0.0.0:8502
```
**The logger:**
```
kobi@desk1:~/Projects/node-modbus-serial/examples(master)$ node logger.js 
Connected
Receive: [ 8005, 8006, 8007, 8008 ]
Receive: [ 8005, 8006, 8007, 8008 ]
Receive: [ 8005, 8006, 8007, 8008 ]
Receive: [ 8005, 8006, 8007, 8008 ]
Receive: [ 8005, 8006, 8007, 8008 ]
we have to reconnect
Port Not Open
Cannot read property 'isOpen' of undefined
Cannot read property 'isOpen' of undefined
we have to reconnect
Port Not Open
Cannot read property 'isOpen' of undefined
Cannot read property 'isOpen' of undefined
we have to reconnect
connect ECONNREFUSED 127.0.0.1:8502
Cannot read property 'isOpen' of undefined
Cannot read property 'isOpen' of undefined
Cannot read property 'isOpen' of undefined
we have to reconnect
Port Not Open
Cannot read property 'isOpen' of undefined
Cannot read property 'isOpen' of undefined
Connected
Receive: [ 8005, 8006, 8007, 8008 ]
Timed out
Receive: [ 8005, 8006, 8007, 8008 ]
Receive: [ 8005, 8006, 8007, 8008 ]
Receive: [ 8005, 8006, 8007, 8008 ]
Receive: [ 8005, 8006, 8007, 8008 ]
Receive: [ 8005, 8006, 8007, 8008 ]
```

**Comment by yaacov** [comment]
@joshuatreenl can you check with the example server.js like I did above ^^
the logger should be set to 127.0.0.1:8502.

Maybe the reason we can not make it work on your side is a side-effect of not building the code ?
If running the same test I made on my desktop ( see above ) fails on your IOT2040 than we can ask @biancode to make a package that you could try ?

**Comment by biancode** [comment]
I released node-red-contrib-modbus@1.0.9-iota, which is downloading the newest version of modbus-serial on reinstalling now, but if it becomes stable I'll set it back to a fixed version.

**Comment by joshuatreenl** [comment]
@yaacov  Interesting!

I did get the same error!! The logger stopped immediately. See log: 
[20170331 1628 server_logger_js.txt](https://github.com/yaacov/node-modbus-serial/files/885958/20170331.1628.server_logger_js.txt)

**Comment by joshuatreenl** [comment]
@biancode I will try to install the package. I think like this:

- Remove node-red-modbus branch
- npm install node-red-contrib-modbus@1.0.9-iota --unsafe-perm --build-from-source

**Comment by yaacov** [comment]
@biancode see that I also catch the error of the readRegisters:
https://github.com/yaacov/node-modbus-serial/blob/master/examples/logger.js#L48
We didn't do that before, do you do that in node-red ?

If you do, than we can ask @joshuatreenl to install the new version of nod-red-modubs with modbus-serial 5.2.5 ( it's already on npm :-) )
If you don't currently catch the errors from readRegisters, add this, and than we will ask @joshuatreenl to try it.

**Comment by biancode** [comment]
@yaacov Yes, the Node-RED package has the catch function on reading, writing, and connecting.

**Comment by joshuatreenl** [comment]
@biancode FYI If I install the package I've got the following warnings:

 root@iot2000:/usr/lib/node_modules# npm install node-red-contrib-modbus@1.0.9-iota --unsafe-perm --build-from-source
WARN engine node-red-contrib-modbus@1.0.9-iota: wanted: {"node":">=6.9"} (current: {"node":"4.2.4","npm":"2.14.12"})
WARN engine node-modbus@3.2.6: wanted: {"node":">=4.7.0"} (current: {"node":"4.2.4","npm":"2.14.12"})
|

I'll hope these will be gone when image v2.1.3 is released as noticed before.

**Comment by biancode** [comment]
@joshuatreenl - yes, that warning is if your node.js is out of tested and supported range - serialport 4.0.7 needs that versions, if you want to be stable.

**Comment by yaacov** [comment]
p.s

@joshuatreenl when reinstalling you need to remove all the directories we copied changed ... while trying to solve this, before reinstall.

**Comment by joshuatreenl** [comment]
Still building... 

I need version >6.9 (i think) because if I made use of the Node-Red Modbus server the server gives an error of buffer.alloc. 

>@joshuatreenl when reinstalling you need to remove all the directories we copied changed ... while trying to solve this, before reinstall.<
I removed some directories. If the build is not working I will make a fresh image.

**Comment by joshuatreenl** [comment]
These messages appears during install: 

root@iot2000:/usr/lib/node_modules# npm install node-red-contrib-modbus@1.0.9-iota --unsafe-perm --build-from-source
WARN engine node-red-contrib-modbus@1.0.9-iota: wanted: {"node":">=6.9"} (current: {"node":"4.2.4","npm":"2.14.12"})
WARN engine node-modbus@3.2.6: wanted: {"node":">=4.7.0"} (current: {"node":"4.2.4","npm":"2.14.12"})
|
> serialport@4.0.7 install /usr/lib/node_modules/node-red-contrib-modbus/node_modules/serialport
> node-pre-gyp install --fallback-to-build

make: Entering directory '/usr/lib/node_modules/node-red-contrib-modbus/node_modules/serialport/build'
  CXX(target) Release/obj.target/serialport/src/serialport.o
  CXX(target) Release/obj.target/serialport/src/serialport_unix.o
  CXX(target) Release/obj.target/serialport/src/serialport_poller.o
  SOLINK_MODULE(target) Release/obj.target/serialport.node
  COPY Release/serialport.node
make: Leaving directory '/usr/lib/node_modules/node-red-contrib-modbus/node_modules/serialport/build'
npm WARN unmet dependency /usr/lib/node_modules/node-red/node_modules/node-red-node-serialport/node_modules/serialport/node_modules/tar-pack requires debug@'~2.2.0' but will load
npm WARN unmet dependency /usr/lib/node_modules/node-red/node_modules/node-red-node-serialport/node_modules/serialport/node_modules/debug,
npm WARN unmet dependency which is version 2.3.3
node-red-contrib-modbus@1.0.9-iota node-red-contrib-modbus
├── stately.js@1.3.0
├── modbus-serial@5.2.5
├── node-modbus@3.2.6 (net@1.0.2, stampit-log@0.3.0, stampit-event-bus@0.1.1, stampit-state-machine@0.2.1, crc@3.4.4, bluebird@3.5.0)
├── stampit@2.1.2 (supermixer@1.0.3, lodash@3.10.1)
└── serialport@4.0.7 (bindings@1.2.1, commander@2.9.0, lie@3.1.1, nan@2.5.1, object.assign@4.0.4)

**Comment by biancode** [comment]
If you are not in trouble with other nodes, then you can follow that [Wiki](https://github.com/biancode/node-red-contrib-modbus/wiki/Raspberry-PI2-and-PI3-hints)

**Comment by joshuatreenl** [comment]
There was also a comment on the Siemens side. Somebody tried to do that and got several errors. 'The developers' have promised to put in version 6.9.2 into image v2.1.3. Of course I am not happy about, because I want to do it by myself. Maybe if I have more experience I will tru to make an image myself.

**Comment by joshuatreenl** [comment]
GREAT IT WORKS! 
I will make a logfile via the DEBUG option.

**Comment by yaacov** [comment]
> GREAT IT WORKS!

closed #92 🍰

**Comment by joshuatreenl** [comment]
Sorry again...

**Comment by joshuatreenl** [comment]
I will make fresh image.

**Comment by yaacov** [comment]
> Sorry again...
@joshuatreenl np, so we did need to build .... now I will know :-)

**Comment by joshuatreenl** [comment]
After I 'installed' the iota version I did also make a test with the server <--> logger. I've got the same result. The logger stops after killing the server (^C).

**Comment by yaacov** [comment]
> NO IT DOESN'T

It may be the nodejs version ... if you can try with a newer version, it will help to understand what is going on.

**Comment by joshuatreenl** [comment]
>It may be the nodejs version ... if you can try with a newer version, it will help to understand what is going on.<

The last thing I want to do: 

- Installing the fresh image and load the iota version.
- If this doesn't work we'll have to wait for the image update... 

We (you) put several time in it. I'm pretty sure (I don't know why) it will be resolved with the updated node.js version.

**Comment by yaacov** [comment]
> I'm pretty sure (I don't know why) it will be resolved with the updated node.js version.

4.2 is very old ... current long term version is v6.10.1 and regular version is v7.8.0, it looks like a good guess :-)

**Comment by joshuatreenl** [comment]
I have also a Pi and I will try on that device (with updated node.js version). 
The IOT2040 is pretty new and it should have some improvements I'm afraid...

**Comment by joshuatreenl** [comment]
A lots of errors...
[install.TXT](https://github.com/yaacov/node-modbus-serial/files/886160/install.TXT)

I will try: 
npm install node-red-contrib-modbus@1.0.9-iota --unsafe-perm --build-from-source

**Comment by biancode** [comment]
I would try to install:

```
sudo npm cache clean -f

sudo npm install -g n

sudo n 6.9.2
```

or 

```
sudo npm cache clean -f

sudo npm install -g n

sudo n 4.7.3
```

and if it doesn't work you can go back the same way:

```
sudo npm cache clean -f

sudo npm install -g n

sudo n 4.2.4
```

**Comment by yaacov** [comment]
> sudo npm install -g n

His node version is pre 4.7, shouldn't he use the script you suggested here:
https://github.com/biancode/node-red-contrib-modbus/wiki/Raspberry-PI2-and-PI3-hints#nodejs-is-470

**Comment by joshuatreenl** [comment]
all above it's not working. Sudo is not working and n gives also problems.
Because its new to Siemens (i think)...they have installed the Yocto distribution. In my opinion it's primitive now, but in the future I think, because of all the discussion, things will be improving. 
The folowing discussion was started: 
screenshot636

screenshot636

There's also a discussion started "how can i build my own image" 
So I have to be wait... 

What I want to do is to install my Rasp with the Node Red software and check if this device in combination with the PLC also have some troubles. I'll let you know the status.

Remark; The build with --unsafe-perm etc. gives the same problems.

**Comment by joshuatreenl** [comment]
The reason I want to be using the IOT2040 because it's industrial, Siemens have a 'good' name...

**Comment by joshuatreenl** [comment]
Ok next level
- installed the Raspberry Pi (Raspbian Jessie)
- updated several packages (don't know what all have been updated...)
- set the node to version v6.9.5 
- Installed the node-red-contrib-modbus@1.0.9-iota -- etc.  
- Started node-red 
- Made a ModbusRead connection to the Siemens PLC 
- Disconnect the server for at least 30 seconds -> see node-red react failure->initialize->failure-> etc
- Connect the server again 
- After two attempts the reconnection was established. 

Finally I can say IT WORKS! 

Conclusion: 
The problem is the version of node v4.2.4... 
(Now I'll have to wait for the update...)

**Comment by yaacov** [comment]
> Finally I can say IT WORKS!

yeeee... closing #92 again :-)

p.s.
We have a new version of node-modbus-serial v5.2.6 that fix a bug of trying to write to closed port, this bug began at v5.2.4 when the odd behaviour started. Maybe the new version with the bug fix will work on older node version.

**Comment by yaacov** [comment]
link to code:
https://github.com/yaacov/node-modbus-serial/archive/master.zip

**Comment by biancode** [comment]
node-red-contrib-modbus@1.0.9-kappa with fixed version of modbus-serial 5.2.6

**Comment by joshuatreenl** [comment]
Installation node-red-contrib-modbus@1.0.9-kappa 
- Build from scratch; image v2.1.2 Siemens (Yocto) installed on sd-card
- Expand file system (use of 15 Gb sd-card space enabled)
- Installation node-red-contrib-modbus@1.0.9-kappa. Result: see 
[20170401 1055 1_0_9_kappa_install.txt](https://github.com/yaacov/node-modbus-serial/files/887498/20170401.1055.1_0_9_kappa_install.txt)

In my opinion:
Because of the node version 4.2.4, which is installed in the v2.1.2 image, serial version 5.2.6 is not installed. Instead version 4.7.0 is installed.

After installation I performed a test with node-red. Result: see
[20170401 1130 1_0_9_kappa_testing node red.txt](https://github.com/yaacov/node-modbus-serial/files/887500/20170401.1130.1_0_9_kappa_testing.node.red.txt)

Observation:
There is no reconnection, ModbusRead stays on "initialize". After I send ^C the state is closed.

In my opinion:
- The ECONNRESET signal is detected now. In the previous version this was not the case.

**Comment by yaacov** [comment]
> If I install the ModbusServer then a BufferAlloc error appears

Buffer.alloc is available from node v5.10 , you will have to wait for new image :-(

**Comment by joshuatreenl** [comment]
@yaacov I've put a message on the Siemens forum to ask if there is someone has updated node without waiting for a new image. I know that I can make a build myself, but it is clear to me that there should be a procedure how to update. That's more flexible. I read about what @biancode mentioned earlier, but this doesn't work.

**Comment by yaacov** [comment]
did you try to method @biancode described for pre v4.7 node ?
( it does not use the `n` script )

> nodejs is <4.7.0
> curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
> sudo npm install -g nodejs

**Comment by joshuatreenl** [comment]
sudo is not working on the IOT2000. I think i don't needed, but then of course the -E bash makes no sense... 
If I leave it out then the curl command is doing nothing (i think). but of course bash is not executed...

Commands and replies:

root@iot2000:/usr/lib# curl -sL https://deb/nodesource.com/setup_6.x
root@iot2000:/usr/lib# npm install -g nodejs
npm WARN unmet dependency /usr/lib/node_modules/node-red/node_modules/node-red-node-serialport/node_modules/serialport/node_modules/tar-pack requires debug@'~2.2.0' but will load
npm WARN unmet dependency /usr/lib/node_modules/node-red/node_modules/node-red-node-serialport/node_modules/serialport/node_modules/debug,
npm WARN unmet dependency which is version 2.3.3
nodejs@0.0.0 /usr/lib/node_modules/nodejs

- I don't know what exactly happens :-) 
- I don't know if i it is installed in the right directory. 
- After reboot still version 4.2.4 is installed.

**Comment by yaacov** [comment]
you can try:
`curl -sL https://deb.nodesource.com/setup_6.x | bash -`

**Comment by joshuatreenl** [comment]
I did but I don't know (maybe you know) there should be something happens like output to the console. What I encounter is that after giving that command the prompt will be returned, no output:

root@iot2000:~# curl -sL https://deb/nodesource.com/setup_6.x | bash -
root@iot2000:~#

**Comment by joshuatreenl** [comment]
With wget (mentioned in the source of https://... ) I got: 
wget: server returned error: HTTP/1.1 400 Bad Request

**Comment by yaacov** [comment]
> I did but I don't know (maybe you know) there should be something happens like output to the console. 

Their should have been, I do not know either :-)

last thing (*) I can think of is to try the intel 32bit nodejs official binaries, 
the cpu on iot2040 is intel 32bit quark, I do not know if it's compatible with regular intel 32bit, but why not try ?

https://nodejs.org/dist/v6.10.1/node-v6.10.1-linux-x86.tar.xz
a. extract it
b. make a copy of the `node` and `npm` in the `/usr/bin/ `dir ( in case this does not work :-) )
c. replace the `node` and `npm` files in /`usr/bin` with the ones from the nodejs site

(*) It will be very funny if it works ... this is not the way to do it :-)

**Comment by yaacov** [comment]
According to the wikipedia, this trick might actually work:
https://en.wikipedia.org/wiki/Intel_Quark

> The CPU instruction set is the same as a Pentium (P54C/i586) CPU.

**Comment by yaacov** [comment]
you will also have to copy the `lib` directory contents to the `/usr/lib` direcotry in the controller

**Comment by joshuatreenl** [comment]
LOL
- Copied the include also (/home/root/6.10.1
- Copied the npm and node 
- Copied the lib directory 
- Reboot

root@iot2000: node -v
Illegal instruction
root@iot2000: npm
Illegal instruction

Almost...

**Comment by yaacov** [comment]
> Almost...

Well, we tried :-)

**Pull request merged**
