### PR TITLE
Feature/read device identification

### PR DESCRIPTION
**Pull request by eeerin**
Implementing modbus read device identification based on [page 44 of this text](http://www.modbus.org/docs/Modbus_Application_Protocol_V1_1b.pdf)

### CODE REVIEW

**Comment by eeerin** [comment]
https://github.com/yaacov/node-modbus-serial/issues/315 attempting to solve this issue.

**Comment by yaacov** [comment]
Wow, thanks :heart: 

If you need a new version comment here :+1:

**Comment by eeerin** [comment]
@yaacov before we put a new version on this let me test it with an actual device.

**Comment by yadidgarbo** [comment]
@eeerin 
Hi Eeerin,

could you test your version on a device?
I have a device that is able to return function 43.

Could you publish your version?


`
var ModbusRTU = require("modbus-serial");
var vector = {
    readDeviceIdentification: function(addr) {
        return {
            0x00: "MyVendorName",
            0x01: "MyProductCode",
            0x02: "MyMajorMinorRevision",
            0x05: "MyModelName",
            0x97: "MyExtendedObject1",
            0xAB: "MyExtendedObject2"
        };
    }
};

var serverTCP = new ModbusRTU.ServerTCP(vector, { host: "192.168.1.21", port: 502, debug: true, unitID: 1 });
 
serverTCP.on("socketError", function(err){
    console.error(err);
});
`
I get the response that the IP address is not available:-(

**Comment by yaacov** [comment]
@yadidgarbo hi, this PR has continued here - https://github.com/yaacov/node-modbus-serial/pull/321
Please continue in #321.

**Pull request merged**
