### PR TITLE
Bump serial port to 12.0.0

### PR DESCRIPTION
**Pull request by yaacov**
Bumping dependencies versions

### CODE REVIEW

**Comment by yaacov** [comment]
@Jalle19 hi, can you check if this version bumps change something for your use case ?

**Comment by yaacov** [comment]
Closing,
seems that reverting #507 fixed the issue.

**Comment by Jalle19** [comment]
Did you force push away the changes or what happened?

**Comment by yaacov** [comment]
> Did you force push away the changes or what happened?

yes, I reverted #507 and #508 and forced push it.

**Comment by 1038642892** [comment]
Can I get a bit more detail please @Jalle19 as to what broke?

**Comment by Jalle19** [comment]
After reading a couple of registers, all Modbus requests started timing out. I don't have an easy setup for debugging Modbus (no test devices), so I can't really give more information.

**Comment by Jalle19** [comment]
https://github.com/Jalle19/eda-modbus-bridge/blob/master/eda-modbus-bridge.mjs#L91 
https://github.com/Jalle19/eda-modbus-bridge/blob/master/app/modbus.mjs

**Comment by 1038642892** [comment]
@Jalle19 thanks, which server/device set up are you using? Looking at the debug log, is there only one query that times out? Do the others return OK?

**Pull request closed without merging**
