### PR TITLE
Add options to ModbusRTU.d.ts

### PR DESCRIPTION
**Pull request by adam-nielsen**
As requested, many thanks for the quick merge!

### CODE REVIEW

**Comment by yaacov** [comment]
Thanks :tada:

**Comment by yaacov** [comment]
@adam-nielsen do you need an npm version ?

**Comment by adam-nielsen** [comment]
@yaacov If you can do an NPM version that would save me a lot of effort!

**Comment by yaacov** [comment]
@adam-nielsen 
https://github.com/yaacov/node-modbus-serial/releases/tag/v7.7.3

https://www.npmjs.com/package/modbus-serial/v/7.7.3
https://www.npmjs.com/package/modbus-serial/v/7.7.3-no-serial-port

**Comment by adam-nielsen** [comment]
Thank you! :tada:

**Pull request merged**
