### PR TITLE
Remove Node.js engine dependency and instead add a compatibility note

### PR DESCRIPTION
**Pull request by dom-white**
Pull request for issue #166

### CODE REVIEW

**Comment by yaacov** [comment]
🌷 Thanks 👍

**Comment by dom-white** [comment]
Thanks for merging in. Great module BTW

**Comment by yaacov** [comment]
p.s.
do you need a new version in npm ?

**Comment by dom-white** [comment]
It would be handy if its not too much trouble

**Comment by yaacov** [comment]
https://www.npmjs.com/package/modbus-serial v7.0.2 🌺

**Comment by dom-white** [comment]
Thank you

**Pull request merged**
